### ISSUE TITLE
Does this require a minimum TypeScript version?

### ISSUE THREAD

**Issue by dbalatero** [jetify-com/typeid-js#10]
My company is stuck on TS 4.9.4, and out of the box this library is broken.

Is there a minimum TS version that should be documented in the `README.md`? I see `typescript` is at some `5.x` version in the `package.json`.

Build errors:

```
../../../node_modules/typeid-js/dist/typeid.d.ts:1:22 - error TS1139: Type parameter declaration expected.

1 declare class TypeID<const T extends string> {
                       ~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:1:30 - error TS1005: ',' expected.

1 declare class TypeID<const T extends string> {
                               ~~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:1:44 - error TS1005: ',' expected.

1 declare class TypeID<const T extends string> {
                                             ~

../../../node_modules/typeid-js/dist/typeid.d.ts:2:19 - error TS1005: ',' expected.

2     private prefix;
                    ~

../../../node_modules/typeid-js/dist/typeid.d.ts:3:19 - error TS1005: ',' expected.

3     private suffix;
                    ~

../../../node_modules/typeid-js/dist/typeid.d.ts:5:5 - error TS1005: ',' expected.

5     getType(): T;
      ~~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:6:5 - error TS1005: ',' expected.

6     getSuffix(): string;
      ~~~~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:7:5 - error TS1005: ',' expected.

7     asType<const U extends string>(prefix: U): TypeID<U>;
      ~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:7:12 - error TS1139: Type parameter declaration expected.

7     asType<const U extends string>(prefix: U): TypeID<U>;
             ~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:7:18 - error TS1005: ':' expected.

7     asType<const U extends string>(prefix: U): TypeID<U>;
                   ~

../../../node_modules/typeid-js/dist/typeid.d.ts:7:20 - error TS1005: ',' expected.

7     asType<const U extends string>(prefix: U): TypeID<U>;
                     ~~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:7:28 - error TS1005: ':' expected.

7     asType<const U extends string>(prefix: U): TypeID<U>;
                             ~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:7:42 - error TS1005: ')' expected.

7     asType<const U extends string>(prefix: U): TypeID<U>;
                                           ~

../../../node_modules/typeid-js/dist/typeid.d.ts:7:45 - error TS1005: ',' expected.

7     asType<const U extends string>(prefix: U): TypeID<U>;
                                              ~

../../../node_modules/typeid-js/dist/typeid.d.ts:7:46 - error TS1136: Property assignment expected.

7     asType<const U extends string>(prefix: U): TypeID<U>;
                                               ~

../../../node_modules/typeid-js/dist/typeid.d.ts:7:57 - error TS1005: '(' expected.

7     asType<const U extends string>(prefix: U): TypeID<U>;
                                                          ~

../../../node_modules/typeid-js/dist/typeid.d.ts:8:5 - error TS1005: ',' expected.

8     toUUIDBytes(): Uint8Array;
      ~~~~~~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:9:5 - error TS1005: ',' expected.

9     toUUID(): string;
      ~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:10:5 - error TS1005: ',' expected.

10     toString(): `${T}_${string}` | string;
       ~~~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:11:5 - error TS1005: ',' expected.

11     static fromString<const T extends string>(str: string): TypeID<T>;
       ~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:11:23 - error TS1139: Type parameter declaration expected.

11     static fromString<const T extends string>(str: string): TypeID<T>;
                         ~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:11:29 - error TS1005: ':' expected.

11     static fromString<const T extends string>(str: string): TypeID<T>;
                               ~

../../../node_modules/typeid-js/dist/typeid.d.ts:11:31 - error TS1005: ',' expected.

11     static fromString<const T extends string>(str: string): TypeID<T>;
                                 ~~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:11:39 - error TS1005: ':' expected.

11     static fromString<const T extends string>(str: string): TypeID<T>;
                                         ~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:11:50 - error TS1005: ')' expected.

11     static fromString<const T extends string>(str: string): TypeID<T>;
                                                    ~

../../../node_modules/typeid-js/dist/typeid.d.ts:11:58 - error TS1005: ',' expected.

11     static fromString<const T extends string>(str: string): TypeID<T>;
                                                            ~

../../../node_modules/typeid-js/dist/typeid.d.ts:11:59 - error TS1136: Property assignment expected.

11     static fromString<const T extends string>(str: string): TypeID<T>;
                                                             ~

../../../node_modules/typeid-js/dist/typeid.d.ts:11:70 - error TS1005: '(' expected.

11     static fromString<const T extends string>(str: string): TypeID<T>;
                                                                        ~

../../../node_modules/typeid-js/dist/typeid.d.ts:12:5 - error TS1005: ',' expected.

12     static fromUUIDBytes<const T extends string>(prefix: T, bytes: Uint8Array): TypeID<T>;
       ~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:12:26 - error TS1139: Type parameter declaration expected.

12     static fromUUIDBytes<const T extends string>(prefix: T, bytes: Uint8Array): TypeID<T>;
                            ~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:12:32 - error TS1005: ':' expected.

12     static fromUUIDBytes<const T extends string>(prefix: T, bytes: Uint8Array): TypeID<T>;
                                  ~

../../../node_modules/typeid-js/dist/typeid.d.ts:12:34 - error TS1005: ',' expected.

12     static fromUUIDBytes<const T extends string>(prefix: T, bytes: Uint8Array): TypeID<T>;
                                    ~~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:12:42 - error TS1005: ':' expected.

12     static fromUUIDBytes<const T extends string>(prefix: T, bytes: Uint8Array): TypeID<T>;
                                            ~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:12:56 - error TS1005: ')' expected.

12     static fromUUIDBytes<const T extends string>(prefix: T, bytes: Uint8Array): TypeID<T>;
                                                          ~

../../../node_modules/typeid-js/dist/typeid.d.ts:12:78 - error TS1005: ',' expected.

12     static fromUUIDBytes<const T extends string>(prefix: T, bytes: Uint8Array): TypeID<T>;
                                                                                ~

../../../node_modules/typeid-js/dist/typeid.d.ts:12:79 - error TS1136: Property assignment expected.

12     static fromUUIDBytes<const T extends string>(prefix: T, bytes: Uint8Array): TypeID<T>;
                                                                                 ~

../../../node_modules/typeid-js/dist/typeid.d.ts:12:90 - error TS1005: '(' expected.

12     static fromUUIDBytes<const T extends string>(prefix: T, bytes: Uint8Array): TypeID<T>;
                                                                                            ~

../../../node_modules/typeid-js/dist/typeid.d.ts:13:5 - error TS1005: ',' expected.

13     static fromUUID<const T extends string>(prefix: T, uuid: string): TypeID<T>;
       ~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:13:21 - error TS1139: Type parameter declaration expected.

13     static fromUUID<const T extends string>(prefix: T, uuid: string): TypeID<T>;
                       ~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:13:27 - error TS1005: ':' expected.

13     static fromUUID<const T extends string>(prefix: T, uuid: string): TypeID<T>;
                             ~

../../../node_modules/typeid-js/dist/typeid.d.ts:13:29 - error TS1005: ',' expected.

13     static fromUUID<const T extends string>(prefix: T, uuid: string): TypeID<T>;
                               ~~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:13:37 - error TS1005: ':' expected.

13     static fromUUID<const T extends string>(prefix: T, uuid: string): TypeID<T>;
                                       ~~~~~~

../../../node_modules/typeid-js/dist/typeid.d.ts:13:51 - error TS1005: ')' expected.

13     static fromUUID<const T extends string>(prefix: T, uuid: string): TypeID<T>;
                                                     ~

../../../node_modules/typeid-js/dist/typeid.d.ts:13:68 - error TS1005: ',' expected.

13     static fromUUID<const T extends string>(prefix: T, uuid: string): TypeID<T>;
                                                                      ~

../../../node_modules/typeid-js/dist/typeid.d.ts:13:69 - error TS1136: Property assignment expected.

13     static fromUUID<const T extends string>(prefix: T, uuid: string): TypeID<T>;
                                                                       ~

../../../node_modules/typeid-js/dist/typeid.d.ts:13:80 - error TS1005: '(' expected.

13     static fromUUID<const T extends string>(prefix: T, uuid: string): TypeID<T>;
                                                                                  ~


Found 46 errors in the same file, starting at: ../../../node_modules/typeid-js/dist/typeid.d.ts:1
```

**Comment by loreto** [comment]
FYI @LucilleH

**Comment by LucilleH** [comment]
@dbalatero yes it requires `typescript@^5.0.0`. I will update the README 👍

**Comment by dbalatero** [comment]
Thanks, I might use the community version until we can get on TS 5.0 then (provided the community version works with 4.9).
